export const queryKeys = {
  auth: {
    all: ['auth'] as const,
    session: () => [...queryKeys.auth.all, 'session'] as const,
    sessions: () => [...queryKeys.auth.all, 'sessions'] as const,
  },
  claims: {
    all: ['claims'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.claims.all, 'list', filters] as const,
    detail: (id: string) => [...queryKeys.claims.all, 'detail', id] as const,
    templates: () => [...queryKeys.claims.all, 'templates'] as const,
    suggestions: (id: string) => [...queryKeys.claims.all, 'suggestions', id] as const,
  },
  patients: {
    all: ['patients'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.patients.all, 'list', filters] as const,
    detail: (id: string) => [...queryKeys.patients.all, 'detail', id] as const,
    search: (query: string) => [...queryKeys.patients.all, 'search', query] as const,
    recent: () => [...queryKeys.patients.all, 'recent'] as const,
    eligibility: (id: string) => [...queryKeys.patients.all, 'eligibility', id] as const,
  },
  providers: {
    all: ['providers'] as const,
    profile: () => [...queryKeys.providers.all, 'profile'] as const,
    businessArrangements: () => [...queryKeys.providers.all, 'ba'] as const,
    locations: () => [...queryKeys.providers.all, 'locations'] as const,
    wcbConfig: () => [...queryKeys.providers.all, 'wcb-config'] as const,
    delegates: () => [...queryKeys.providers.all, 'delegates'] as const,
    submissionPreferences: () => [...queryKeys.providers.all, 'submission-prefs'] as const,
    routing: () => [...queryKeys.providers.all, 'routing'] as const,
  },
  reference: {
    all: ['reference'] as const,
    hsc: (query: string) => [...queryKeys.reference.all, 'hsc', query] as const,
    di: (query: string) => [...queryKeys.reference.all, 'di', query] as const,
    modifiers: (hscCode?: string) => [...queryKeys.reference.all, 'modifiers', hscCode] as const,
    functionalCentres: () => [...queryKeys.reference.all, 'fc'] as const,
    referringProviders: (query: string) => [...queryKeys.reference.all, 'referring', query] as const,
    holidays: () => [...queryKeys.reference.all, 'holidays'] as const,
    changes: () => [...queryKeys.reference.all, 'changes'] as const,
    favourites: () => [...queryKeys.reference.all, 'favourites'] as const,
    guidance: (code: string) => [...queryKeys.reference.all, 'guidance', code] as const,
    bundling: (codes: string[]) => [...queryKeys.reference.all, 'bundling', ...codes] as const,
    crosswalk: (icd10Code: string) => [...queryKeys.reference.all, 'crosswalk', icd10Code] as const,
  },
  wcb: {
    all: ['wcb'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.wcb.all, 'list', filters] as const,
    detail: (id: string) => [...queryKeys.wcb.all, 'detail', id] as const,
    formSchema: (formType: string) => [...queryKeys.wcb.all, 'schema', formType] as const,
    batches: () => [...queryKeys.wcb.all, 'batches'] as const,
  },
  batches: {
    all: ['batches'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.batches.all, 'list', filters] as const,
    detail: (id: string) => [...queryKeys.batches.all, 'detail', id] as const,
  },
  analytics: {
    all: ['analytics'] as const,
    revenue: (filters?: Record<string, unknown>) => [...queryKeys.analytics.all, 'revenue', filters] as const,
    rejections: (filters?: Record<string, unknown>) => [...queryKeys.analytics.all, 'rejections', filters] as const,
    aging: (filters?: Record<string, unknown>) => [...queryKeys.analytics.all, 'aging', filters] as const,
    wcb: (filters?: Record<string, unknown>) => [...queryKeys.analytics.all, 'wcb', filters] as const,
    aiCoach: (filters?: Record<string, unknown>) => [...queryKeys.analytics.all, 'ai-coach', filters] as const,
    multiSite: (filters?: Record<string, unknown>) => [...queryKeys.analytics.all, 'multi-site', filters] as const,
    kpi: () => [...queryKeys.analytics.all, 'kpi'] as const,
  },
  reports: {
    all: ['reports'] as const,
    list: (filters?: Record<string, unknown>) => [...queryKeys.reports.all, 'list', filters] as const,
    subscriptions: () => [...queryKeys.reports.all, 'subscriptions'] as const,
  },
  notifications: {
    all: ['notifications'] as const,
    feed: (filters?: Record<string, unknown>) => [...queryKeys.notifications.all, 'feed', filters] as const,
    unreadCount: () => [...queryKeys.notifications.all, 'unread'] as const,
    preferences: () => [...queryKeys.notifications.all, 'preferences'] as const,
  },
  intelligence: {
    all: ['intelligence'] as const,
    suggestions: (claimId: string) => [...queryKeys.intelligence.all, 'suggestions', claimId] as const,
    preferences: () => [...queryKeys.intelligence.all, 'preferences'] as const,
    learningState: () => [...queryKeys.intelligence.all, 'learning'] as const,
    rules: (filters?: Record<string, unknown>) => [...queryKeys.intelligence.all, 'rules', filters] as const,
  },
  onboarding: {
    all: ['onboarding'] as const,
    progress: () => [...queryKeys.onboarding.all, 'progress'] as const,
  },
  subscription: {
    all: ['subscription'] as const,
    status: () => [...queryKeys.subscription.all, 'status'] as const,
    practice: () => [...queryKeys.subscription.all, 'practice'] as const,
    referral: () => [...queryKeys.subscription.all, 'referral'] as const,
  },
  support: {
    all: ['support'] as const,
    articles: (filters?: Record<string, unknown>) => [...queryKeys.support.all, 'articles', filters] as const,
    article: (slug: string) => [...queryKeys.support.all, 'article', slug] as const,
    tickets: (filters?: Record<string, unknown>) => [...queryKeys.support.all, 'tickets', filters] as const,
    ticket: (id: string) => [...queryKeys.support.all, 'ticket', id] as const,
  },
  mobile: {
    all: ['mobile'] as const,
    shifts: (filters?: Record<string, unknown>) => [...queryKeys.mobile.all, 'shifts', filters] as const,
    shift: (id: string) => [...queryKeys.mobile.all, 'shift', id] as const,
    favourites: () => [...queryKeys.mobile.all, 'favourites'] as const,
    schedules: () => [...queryKeys.mobile.all, 'schedules'] as const,
    reconciliation: (shiftId: string) => [...queryKeys.mobile.all, 'reconciliation', shiftId] as const,
  },
} as const;
