// Barrel export for Drizzle DB schemas
export {
  users,
  recoveryCodes,
  sessions,
  invitationTokens,
  delegateLinkages,
  auditLog,
} from './iam.schema.js';
export type {
  InsertUser,
  SelectUser,
  InsertRecoveryCode,
  SelectRecoveryCode,
  InsertSession,
  SelectSession,
  InsertInvitationToken,
  SelectInvitationToken,
  InsertDelegateLinkage,
  SelectDelegateLinkage,
  InsertAuditLog,
  SelectAuditLog,
} from './iam.schema.js';

export {
  subscriptions,
  paymentHistory,
  statusComponents,
  statusIncidents,
  incidentUpdates,
  referralCodes,
  referralRedemptions,
  practices,
  practiceMemberships,
  practiceInvitations,
  imaAmendments,
  imaAmendmentResponses,
  breachRecords,
  breachAffectedCustodians,
  breachUpdates,
  dataDestructionTracking,
} from './platform.schema.js';
export type {
  InsertSubscription,
  SelectSubscription,
  InsertPaymentHistory,
  SelectPaymentHistory,
  InsertStatusComponent,
  SelectStatusComponent,
  InsertStatusIncident,
  SelectStatusIncident,
  InsertIncidentUpdate,
  SelectIncidentUpdate,
  InsertReferralCode,
  SelectReferralCode,
  InsertReferralRedemption,
  SelectReferralRedemption,
  InsertPractice,
  SelectPractice,
  InsertPracticeMembership,
  SelectPracticeMembership,
  InsertPracticeInvitation,
  SelectPracticeInvitation,
  InsertImaAmendment,
  SelectImaAmendment,
  InsertImaAmendmentResponse,
  SelectImaAmendmentResponse,
  InsertBreachRecord,
  SelectBreachRecord,
  InsertBreachAffectedCustodian,
  SelectBreachAffectedCustodian,
  InsertBreachUpdate,
  SelectBreachUpdate,
  InsertDataDestructionTracking,
  SelectDataDestructionTracking,
} from './platform.schema.js';

export {
  notifications,
  emailDeliveryLog,
  notificationTemplates,
  digestQueue,
  notificationPreferences,
} from './notification.schema.js';
export type {
  InsertNotification,
  SelectNotification,
  InsertEmailDeliveryLog,
  SelectEmailDeliveryLog,
  InsertNotificationTemplate,
  SelectNotificationTemplate,
  InsertDigestQueueItem,
  SelectDigestQueueItem,
  InsertNotificationPreference,
  SelectNotificationPreference,
} from './notification.schema.js';

export {
  referenceDataVersions,
  hscCodes,
  wcbCodes,
  modifierDefinitions,
  governingRules,
  functionalCentres,
  diCodes,
  rrnpCommunities,
  pcpcmBaskets,
  statutoryHolidays,
  explanatoryCodes,
  referenceDataStaging,
  icdCrosswalk,
  providerRegistry,
  billingGuidance,
  provincialPhnFormats,
  reciprocalBillingRules,
  anesthesiaRules,
  bundlingRules,
  justificationTemplates,
} from './reference.schema.js';
export type {
  InsertVersion,
  SelectVersion,
  InsertHscCode,
  SelectHscCode,
  InsertWcbCode,
  SelectWcbCode,
  InsertModifierDefinition,
  SelectModifierDefinition,
  InsertGoverningRule,
  SelectGoverningRule,
  InsertFunctionalCentre,
  SelectFunctionalCentre,
  InsertDiCode,
  SelectDiCode,
  InsertRrnpCommunity,
  SelectRrnpCommunity,
  InsertPcpcmBasket,
  SelectPcpcmBasket,
  InsertStatutoryHoliday,
  SelectStatutoryHoliday,
  InsertExplanatoryCode,
  SelectExplanatoryCode,
  InsertReferenceDataStaging,
  SelectReferenceDataStaging,
  InsertIcdCrosswalk,
  SelectIcdCrosswalk,
  InsertProviderRegistry,
  SelectProviderRegistry,
  InsertBillingGuidance,
  SelectBillingGuidance,
  InsertProvincialPhnFormat,
  SelectProvincialPhnFormat,
  InsertReciprocalBillingRule,
  SelectReciprocalBillingRule,
  InsertAnesthesiaRule,
  SelectAnesthesiaRule,
  InsertBundlingRule,
  SelectBundlingRule,
  InsertJustificationTemplate,
  SelectJustificationTemplate,
} from './reference.schema.js';

export {
  providers,
  businessArrangements,
  pcpcmEnrolments,
  practiceLocations,
  wcbConfigurations,
  delegateRelationships,
  submissionPreferences,
  hlinkConfigurations,
  pcpcmPayments,
  pcpcmPanelEstimates,
  baFacilityMappings,
  baScheduleMappings,
} from './provider.schema.js';
export type {
  InsertProvider,
  SelectProvider,
  InsertBa,
  SelectBa,
  InsertPcpcmEnrolment,
  SelectPcpcmEnrolment,
  InsertLocation,
  SelectLocation,
  InsertWcbConfig,
  SelectWcbConfig,
  InsertDelegateRelationship,
  SelectDelegateRelationship,
  InsertSubmissionPreferences,
  SelectSubmissionPreferences,
  InsertHlinkConfig,
  SelectHlinkConfig,
  InsertPcpcmPayment,
  SelectPcpcmPayment,
  InsertPcpcmPanelEstimate,
  SelectPcpcmPanelEstimate,
  InsertBaFacilityMapping,
  SelectBaFacilityMapping,
  InsertBaScheduleMapping,
  SelectBaScheduleMapping,
} from './provider.schema.js';

export {
  patients,
  patientImportBatches,
  patientMergeHistory,
  eligibilityCache,
} from './patient.schema.js';
export type {
  InsertPatient,
  SelectPatient,
  InsertPatientImportBatch,
  SelectPatientImportBatch,
  InsertPatientMergeHistory,
  SelectPatientMergeHistory,
  InsertEligibilityCache,
  SelectEligibilityCache,
} from './patient.schema.js';

export {
  claims,
  fieldMappingTemplates,
  importBatches,
  shifts,
  claimExports,
  claimAuditHistory,
  claimTemplates,
  claimJustifications,
  recentReferrers,
} from './claim.schema.js';
export type {
  InsertClaim,
  SelectClaim,
  InsertFieldMappingTemplate,
  SelectFieldMappingTemplate,
  InsertImportBatch,
  SelectImportBatch,
  InsertShift,
  SelectShift,
  InsertClaimExport,
  SelectClaimExport,
  InsertClaimAuditHistory,
  SelectClaimAuditHistory,
  InsertClaimTemplate,
  SelectClaimTemplate,
  InsertClaimJustification,
  SelectClaimJustification,
  InsertRecentReferrer,
  SelectRecentReferrer,
} from './claim.schema.js';

export { ahcipClaimDetails, ahcipBatches } from './ahcip.schema.js';
export type {
  InsertAhcipClaimDetail,
  SelectAhcipClaimDetail,
  InsertAhcipBatch,
  SelectAhcipBatch,
} from './ahcip.schema.js';

export {
  wcbClaimDetails,
  wcbInjuries,
  wcbPrescriptions,
  wcbConsultations,
  wcbWorkRestrictions,
  wcbInvoiceLines,
  wcbAttachments,
  wcbBatches,
  wcbReturnRecords,
  wcbReturnInvoiceLines,
  wcbRemittanceImports,
  wcbRemittanceRecords,
} from './wcb.schema.js';
export type {
  InsertWcbClaimDetail,
  SelectWcbClaimDetail,
  InsertWcbInjury,
  SelectWcbInjury,
  InsertWcbPrescription,
  SelectWcbPrescription,
  InsertWcbConsultation,
  SelectWcbConsultation,
  InsertWcbWorkRestriction,
  SelectWcbWorkRestriction,
  InsertWcbInvoiceLine,
  SelectWcbInvoiceLine,
  InsertWcbAttachment,
  SelectWcbAttachment,
  InsertWcbBatch,
  SelectWcbBatch,
  InsertWcbReturnRecord,
  SelectWcbReturnRecord,
  InsertWcbReturnInvoiceLine,
  SelectWcbReturnInvoiceLine,
  InsertWcbRemittanceImport,
  SelectWcbRemittanceImport,
  InsertWcbRemittanceRecord,
  SelectWcbRemittanceRecord,
} from './wcb.schema.js';

export {
  aiRules,
  aiProviderLearning,
  aiSpecialtyCohorts,
  aiSuggestionEvents,
} from './intelligence.schema.js';
export type {
  InsertAiRule,
  SelectAiRule,
  InsertAiProviderLearning,
  SelectAiProviderLearning,
  InsertAiSpecialtyCohort,
  SelectAiSpecialtyCohort,
  InsertAiSuggestionEvent,
  SelectAiSuggestionEvent,
  Condition,
  CrossClaimQuery,
  SuggestionTemplate,
} from './intelligence.schema.js';

export {
  analyticsCache,
  generatedReports,
  reportSubscriptions,
} from './analytics.schema.js';
export type {
  InsertAnalyticsCache,
  SelectAnalyticsCache,
  InsertGeneratedReport,
  SelectGeneratedReport,
  InsertReportSubscription,
  SelectReportSubscription,
} from './analytics.schema.js';

export { onboardingProgress, imaRecords } from './onboarding.schema.js';
export type {
  InsertOnboardingProgress,
  SelectOnboardingProgress,
  InsertImaRecord,
  SelectImaRecord,
} from './onboarding.schema.js';

export {
  shiftSchedules,
  edShifts,
  edShiftEncounters,
  favouriteCodes,
} from './mobile.schema.js';
export type {
  InsertShiftSchedule,
  SelectShiftSchedule,
  InsertEdShift,
  SelectEdShift,
  InsertEdShiftEncounter,
  SelectEdShiftEncounter,
  InsertFavouriteCode,
  SelectFavouriteCode,
} from './mobile.schema.js';

export { supportTickets, helpArticles, articleFeedback } from './support.schema.js';
export type {
  InsertSupportTicket,
  SelectSupportTicket,
  InsertHelpArticle,
  SelectHelpArticle,
  InsertArticleFeedback,
  SelectArticleFeedback,
} from './support.schema.js';
