// Barrel export for Drizzle DB schemas
export {
  users,
  recoveryCodes,
  sessions,
  invitationTokens,
  delegateLinkages,
  auditLog,
} from './iam.schema.js';
export type {
  InsertUser,
  SelectUser,
  InsertRecoveryCode,
  SelectRecoveryCode,
  InsertSession,
  SelectSession,
  InsertInvitationToken,
  SelectInvitationToken,
  InsertDelegateLinkage,
  SelectDelegateLinkage,
  InsertAuditLog,
  SelectAuditLog,
} from './iam.schema.js';

export {
  subscriptions,
  paymentHistory,
  statusComponents,
  statusIncidents,
  incidentUpdates,
  referralCodes,
  referralRedemptions,
} from './platform.schema.js';
export type {
  InsertSubscription,
  SelectSubscription,
  InsertPaymentHistory,
  SelectPaymentHistory,
  InsertStatusComponent,
  SelectStatusComponent,
  InsertStatusIncident,
  SelectStatusIncident,
  InsertIncidentUpdate,
  SelectIncidentUpdate,
  InsertReferralCode,
  SelectReferralCode,
  InsertReferralRedemption,
  SelectReferralRedemption,
} from './platform.schema.js';

export {
  notifications,
  emailDeliveryLog,
  notificationTemplates,
  digestQueue,
  notificationPreferences,
} from './notification.schema.js';
export type {
  InsertNotification,
  SelectNotification,
  InsertEmailDeliveryLog,
  SelectEmailDeliveryLog,
  InsertNotificationTemplate,
  SelectNotificationTemplate,
  InsertDigestQueueItem,
  SelectDigestQueueItem,
  InsertNotificationPreference,
  SelectNotificationPreference,
} from './notification.schema.js';

export {
  referenceDataVersions,
  hscCodes,
  wcbCodes,
  modifierDefinitions,
  governingRules,
  functionalCentres,
  diCodes,
  rrnpCommunities,
  pcpcmBaskets,
  statutoryHolidays,
  explanatoryCodes,
  referenceDataStaging,
} from './reference.schema.js';
export type {
  InsertVersion,
  SelectVersion,
  InsertHscCode,
  SelectHscCode,
  InsertWcbCode,
  SelectWcbCode,
  InsertModifierDefinition,
  SelectModifierDefinition,
  InsertGoverningRule,
  SelectGoverningRule,
  InsertFunctionalCentre,
  SelectFunctionalCentre,
  InsertDiCode,
  SelectDiCode,
  InsertRrnpCommunity,
  SelectRrnpCommunity,
  InsertPcpcmBasket,
  SelectPcpcmBasket,
  InsertStatutoryHoliday,
  SelectStatutoryHoliday,
  InsertExplanatoryCode,
  SelectExplanatoryCode,
  InsertReferenceDataStaging,
  SelectReferenceDataStaging,
} from './reference.schema.js';
