// Barrel export for Drizzle DB schemas
export {
  users,
  recoveryCodes,
  sessions,
  invitationTokens,
  delegateLinkages,
  auditLog,
} from './iam.schema.js';
export type {
  InsertUser,
  SelectUser,
  InsertRecoveryCode,
  SelectRecoveryCode,
  InsertSession,
  SelectSession,
  InsertInvitationToken,
  SelectInvitationToken,
  InsertDelegateLinkage,
  SelectDelegateLinkage,
  InsertAuditLog,
  SelectAuditLog,
} from './iam.schema.js';

export {
  subscriptions,
  paymentHistory,
  statusComponents,
  statusIncidents,
  incidentUpdates,
  referralCodes,
  referralRedemptions,
} from './platform.schema.js';
export type {
  InsertSubscription,
  SelectSubscription,
  InsertPaymentHistory,
  SelectPaymentHistory,
  InsertStatusComponent,
  SelectStatusComponent,
  InsertStatusIncident,
  SelectStatusIncident,
  InsertIncidentUpdate,
  SelectIncidentUpdate,
  InsertReferralCode,
  SelectReferralCode,
  InsertReferralRedemption,
  SelectReferralRedemption,
} from './platform.schema.js';

export {
  notifications,
  emailDeliveryLog,
  notificationTemplates,
  digestQueue,
  notificationPreferences,
} from './notification.schema.js';
export type {
  InsertNotification,
  SelectNotification,
  InsertEmailDeliveryLog,
  SelectEmailDeliveryLog,
  InsertNotificationTemplate,
  SelectNotificationTemplate,
  InsertDigestQueueItem,
  SelectDigestQueueItem,
  InsertNotificationPreference,
  SelectNotificationPreference,
} from './notification.schema.js';

export {
  referenceDataVersions,
  hscCodes,
  wcbCodes,
  modifierDefinitions,
  governingRules,
  functionalCentres,
  diCodes,
  rrnpCommunities,
  pcpcmBaskets,
  statutoryHolidays,
  explanatoryCodes,
  referenceDataStaging,
} from './reference.schema.js';
export type {
  InsertVersion,
  SelectVersion,
  InsertHscCode,
  SelectHscCode,
  InsertWcbCode,
  SelectWcbCode,
  InsertModifierDefinition,
  SelectModifierDefinition,
  InsertGoverningRule,
  SelectGoverningRule,
  InsertFunctionalCentre,
  SelectFunctionalCentre,
  InsertDiCode,
  SelectDiCode,
  InsertRrnpCommunity,
  SelectRrnpCommunity,
  InsertPcpcmBasket,
  SelectPcpcmBasket,
  InsertStatutoryHoliday,
  SelectStatutoryHoliday,
  InsertExplanatoryCode,
  SelectExplanatoryCode,
  InsertReferenceDataStaging,
  SelectReferenceDataStaging,
} from './reference.schema.js';

export {
  providers,
  businessArrangements,
  pcpcmEnrolments,
  practiceLocations,
  wcbConfigurations,
  delegateRelationships,
  submissionPreferences,
  hlinkConfigurations,
} from './provider.schema.js';
export type {
  InsertProvider,
  SelectProvider,
  InsertBa,
  SelectBa,
  InsertPcpcmEnrolment,
  SelectPcpcmEnrolment,
  InsertLocation,
  SelectLocation,
  InsertWcbConfig,
  SelectWcbConfig,
  InsertDelegateRelationship,
  SelectDelegateRelationship,
  InsertSubmissionPreferences,
  SelectSubmissionPreferences,
  InsertHlinkConfig,
  SelectHlinkConfig,
} from './provider.schema.js';

export {
  patients,
  patientImportBatches,
  patientMergeHistory,
} from './patient.schema.js';
export type {
  InsertPatient,
  SelectPatient,
  InsertPatientImportBatch,
  SelectPatientImportBatch,
  InsertPatientMergeHistory,
  SelectPatientMergeHistory,
} from './patient.schema.js';

export {
  claims,
  fieldMappingTemplates,
  importBatches,
  shifts,
  claimExports,
  claimAuditHistory,
} from './claim.schema.js';
export type {
  InsertClaim,
  SelectClaim,
  InsertFieldMappingTemplate,
  SelectFieldMappingTemplate,
  InsertImportBatch,
  SelectImportBatch,
  InsertShift,
  SelectShift,
  InsertClaimExport,
  SelectClaimExport,
  InsertClaimAuditHistory,
  SelectClaimAuditHistory,
} from './claim.schema.js';

export { ahcipClaimDetails, ahcipBatches } from './ahcip.schema.js';
export type {
  InsertAhcipClaimDetail,
  SelectAhcipClaimDetail,
  InsertAhcipBatch,
  SelectAhcipBatch,
} from './ahcip.schema.js';

export {
  wcbClaimDetails,
  wcbInjuries,
  wcbPrescriptions,
  wcbConsultations,
  wcbWorkRestrictions,
  wcbInvoiceLines,
  wcbAttachments,
  wcbBatches,
  wcbReturnRecords,
  wcbReturnInvoiceLines,
  wcbRemittanceImports,
  wcbRemittanceRecords,
} from './wcb.schema.js';
export type {
  InsertWcbClaimDetail,
  SelectWcbClaimDetail,
  InsertWcbInjury,
  SelectWcbInjury,
  InsertWcbPrescription,
  SelectWcbPrescription,
  InsertWcbConsultation,
  SelectWcbConsultation,
  InsertWcbWorkRestriction,
  SelectWcbWorkRestriction,
  InsertWcbInvoiceLine,
  SelectWcbInvoiceLine,
  InsertWcbAttachment,
  SelectWcbAttachment,
  InsertWcbBatch,
  SelectWcbBatch,
  InsertWcbReturnRecord,
  SelectWcbReturnRecord,
  InsertWcbReturnInvoiceLine,
  SelectWcbReturnInvoiceLine,
  InsertWcbRemittanceImport,
  SelectWcbRemittanceImport,
  InsertWcbRemittanceRecord,
  SelectWcbRemittanceRecord,
} from './wcb.schema.js';
